[options]
addons_path = /code/odoo_reto/custom_addons
admin_passwd = $pbkdf2-sha512$600000$hNAaA.B8LwUgJMQ4B8BYSw$5ygRXvZ88HkzlaETfg3np5K/k1vue8RQjblM5wDH86Ab.W99vQQlx.qfnFYoOtcxnEujeW3s5jVr1tNDjjh8Cw
db_host = localhost
db_port = 5432
db_user = user
db_password = home_management
db_name = bernie